name: jxcn-newsvideo-poc
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
dependencies:
  - python=3.6
  - pip
  - setuptools
  - ipython
  - ipywidgets
  - cudatoolkit=9.0
  - tqdm
  - wasabi
  - requests
  - pandas
  - matplotlib
  - pytorch
  - torchvision
  - scikit-image
  - ffmpeg
  - opencv
  - python-dotenv
  - pip:
      - scenedetect
